Dont run govuln if it couldnt be installed

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -182,13 +182,13 @@ jobs:
           set +e
           set -o pipefail
 
-          go install golang.org/x/vuln/cmd/govulncheck@v1.6.0
-          if [ $? -ne 0 ]; then
-            echo "Failed to install govulncheck" >> govulncheck.log
+          STATUS=1
+          if go install golang.org/x/vuln/cmd/govulncheck@v1.6.0 2>&1 | tee -a govulncheck.log; then
+            "$(go env GOPATH)/bin/govulncheck" ./... 2>&1 | tee -a govulncheck.log
+            STATUS=$?
+          else
+            echo "Failed to install govulncheck" | tee -a govulncheck.log
           fi
-
-          "$(go env GOPATH)/bin/govulncheck" ./... 2>&1 | tee -a govulncheck.log
-          STATUS=$?
 
           if [ $STATUS -eq 0 ]; then
             exit 0
