make pipeline more robust

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -179,9 +179,18 @@ jobs:
         id: govulncheck
         continue-on-error: true
         run: |
+          set +e
           set -o pipefail
+
           go install golang.org/x/vuln/cmd/govulncheck@v1.6.0
-          if "$(go env GOPATH)/bin/govulncheck" ./... 2>&1 | tee govulncheck.log; then
+          if [ $? -ne 0 ]; then
+            echo "Failed to install govulncheck" >> govulncheck.log
+          fi
+
+          "$(go env GOPATH)/bin/govulncheck" ./... 2>&1 | tee -a govulncheck.log
+          STATUS=$?
+
+          if [ $STATUS -eq 0 ]; then
             exit 0
           fi
 
